version: '3.7'
services:
  # web:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app
  app:
    image: devopstom/lyricgraph:latest
    ports:
      - 8070:8070
    environment:
      HTTP_PORT: 8070
      DATABASE_URL: "host=db user=${DB_USERNAME} password=${DB_PASSWORD} dbname=${DB_NAME} port=5432 sslmode=disable TimeZone=Europe/London"
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
